### ISSUE TITLE
Toggling Caps Lock then pressing Tab untoggles it

### ISSUE THREAD

**Issue by ZimbiX** [shymega/planet-devices#24]
Toggling Caps Lock and then pressing Tab untoggles it. From memory, this was an issue with the Gemini as well. Workaround: Press another key in between, such as Ctrl.

Device: Cosmo Communicator
Android build number: Cosmo-9.0-Planet-02032021-V25

**Comment by Daz-Mataz** [comment]
I can confirm this is the same with the Astro Slide

**Comment by shymega** [comment]
I discussed this with Planet today, and we were able to reproduce the steps on two Astros, but came to the conclusion that this is expected behaviour, and doesn't require a fix. When you look at it from the perspective of using Caps Lock on a normal keyboard, it does make sense for the tab key to act as an 'untoggler'. I'm going to close the issue, as it doesn't affect normal usage, especially alphanumeric characters *after* toggling Caps Lock.

**Comment by Daz-Mataz** [comment]
I know this is a closed issue, but its worth pointing out that the behaviour of Fn+Tab is unlike any of the default shortcuts, in that you have to lift off the Fn key between each press of the tab key to toggle it each time, whereas all the other shortcuts can be pressed in sequence of others i.e Fn+ D and Fn+Del can be activated each in turn without releasing the Fn button.

Also should you switch off the Caps with a Fn+Tab then press tab again, this switches it back on! But as mentioned above if you press any other key after switching Caps off with Fn + Tab the behaviour switches back to a tab.

I will be looking to see if I can remap the Caps combo of Fn + Tab, to something entirely else and just use shift for my uppercase needs.
